In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('rows_to_label.xlsx')

In [3]:
df.head(10)

,Unnamed: 0,Body,UTC_Timestamp,sage_label,selena_label,stephen_label
0,0,i (18f) don’t know what’s wrong with me. i’ve ...,2023-03-15 01:47:11,NaN,NaN,NaN
1,1,For the past 3-4 months my mom has been making...,2023-03-15 03:58:50,NaN,NaN,NaN
2,2,I don't like how there so many bad connotation...,2023-03-13 20:55:28,NaN,NaN,NaN
3,3,I don’t Care who reads this honestly. I’m only...,2023-03-14 09:20:31,NaN,NaN,NaN
4,4,Yea….,2023-03-15 10:38:33,NaN,NaN,NaN
5,5,"Sounds like an overstatement, but it would mak...",2023-03-14 17:45:40,NaN,NaN,NaN
6,6,God I just want to get rid of both of them. \n...,2023-03-16 01:17:15,NaN,NaN,NaN
7,7,\nI grew up with someone through my church whe...,2023-03-14 15:30:15,NaN,NaN,NaN
8,8,Got asked out but just walked away bc i didn't...,2023-03-16 00:46:26,NaN,NaN,NaN
9,9,I just feel incredibly lonely even though I’m ...,2023-03-15 19:58:25,NaN,NaN,NaN

In [4]:
def annotate_helplessness(text):
    count = 0
    # define patterns for learned helplessness
    patterns = ['feel helpless', 'no passion', 'no motivation', 'overwhelmed', 'i am a failure', 'won\'t', 'feel powerless', 'wish', 'no control', 'always fail', 'dissapointed', 'poorly', 'no way out', 'stuck', 'hopeless', 'no hope', 'lonely', 'pity']
    for pattern in patterns:
        if pattern in text:
            count += 1
    if count == 0:
        return 1 # no presence
    elif count == 1:
        return 2 # low presence
    elif count == 2:
        return 3 # moderate presence
    else:
        return 4 # high presence

In [5]:
df['sage_label'] = df['Body'].apply(annotate_helplessness)

In [6]:
df.head(10)

,Unnamed: 0,Body,UTC_Timestamp,sage_label,selena_label,stephen_label
0,0,i (18f) don’t know what’s wrong with me. i’ve ...,2023-03-15 01:47:11,1,NaN,NaN
1,1,For the past 3-4 months my mom has been making...,2023-03-15 03:58:50,1,NaN,NaN
2,2,I don't like how there so many bad connotation...,2023-03-13 20:55:28,1,NaN,NaN
3,3,I don’t Care who reads this honestly. I’m only...,2023-03-14 09:20:31,1,NaN,NaN
4,4,Yea….,2023-03-15 10:38:33,1,NaN,NaN
5,5,"Sounds like an overstatement, but it would mak...",2023-03-14 17:45:40,3,NaN,NaN
6,6,God I just want to get rid of both of them. \n...,2023-03-16 01:17:15,1,NaN,NaN
7,7,\nI grew up with someone through my church whe...,2023-03-14 15:30:15,1,NaN,NaN
8,8,Got asked out but just walked away bc i didn't...,2023-03-16 00:46:26,1,NaN,NaN
9,9,I just feel incredibly lonely even though I’m ...,2023-03-15 19:58:25,2,NaN,NaN

In [7]:
df.to_excel('annotations.xlsx')